# -*- coding: utf-8 -*-
"""Breast Cancer Prediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_IwWaqg1c5b9ka0yUK-0SNkYt4BfpsOj
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

data=pd.read_csv("/content/breast-cancer.csv")

data.size

data.columns

data.shape

data.info()

data.describe()

data.isnull().sum()

data.isnull().sum().sum()

data.head(30)

data.tail(30)

data['diagnosis'] = data['diagnosis'].map({'M': 1, 'B': 0})

data

plt.figure(figsize=(12,10))
sns.heatmap(data.corr(), cmap='coolwarm')
plt.show()

sns.countplot(x='diagnosis', data=data)
plt.show()

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

x=data.drop(columns=['id','diagnosis'])
y=data['diagnosis']

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

x_train.shape

x_test.shape

model=LogisticRegression()

model.fit(x_train,y_train)

y_pred=model.predict(x_test)
print(y_test)
print(y_pred)

from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

acc1=accuracy_score(y_pred,y_test)

print(acc1)

con=confusion_matrix(y_test,y_pred)

print(con)

print(classification_report(y_test,y_pred))

from sklearn.tree import DecisionTreeClassifier

model=DecisionTreeClassifier(random_state=42)

model.fit(x_train,y_train)

y_pred=model.predict(x_test)
acc2=accuracy_score(y_test,y_pred)

print(acc2)

from sklearn.neighbors import KNeighborsClassifier

model=KNeighborsClassifier(n_neighbors=7)

model.fit(x_train,y_train)

y_pred=model.predict(x_test)
acc3=accuracy_score(y_test,y_pred)

print(acc3)

models = ['Logistic Regression', 'Decision Tree', 'KNeighbors']
accuracies = [acc1, acc2, acc3]

plt.bar(models, accuracies, color=['skyblue','lightgreen','salmon'])
plt.ylabel('Accuracy')
plt.title('Model Accuracy Comparison')
plt.ylim(0,1)

plt.show()

